using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ClouDeveloper.HWP
{
    public enum HwpTag
    {
        HWP_TAG_BEGIN = 16,

        HWP_TAG_DOCUMENT_PROPERTIES = 16,
        HWP_TAG_ID_MAPPINGS = 17,
        HWP_TAG_BIN_DATA = 18,
        HWP_TAG_FACE_NAME = 19,
        HWP_TAG_BORDER_FILL = 20,
        HWP_TAG_CHAR_SHAPE = 21,
        HWP_TAG_TAB_DEF = 22,
        HWP_TAG_NUMBERING = 23,
        HWP_TAG_BULLET = 24,
        HWP_TAG_PARA_SHAPE = 25,
        HWP_TAG_STYLE = 26,
        HWP_TAG_DOC_DATA = 27,
        HWP_TAG_DISTRIBUTE_DOC_DATA = 28,
        HWP_TAG_RESERVED_29 = 29,
        HWP_TAG_COMPATIBLE_DOCUMENT = 30,
        HWP_TAG_LAYOUT_COMPATIBILITY = 31,
        HWP_TAG_TRACKCHANGE = 32,

        HWP_TAG_PARA_HEADER = 66,
        HWP_TAG_PARA_TEXT = 67,
        HWP_TAG_PARA_CHAR_SHAPE = 68,
        HWP_TAG_PARA_LINE_SEG = 69,
        HWP_TAG_PARA_RANGE_TAG = 70,
        HWP_TAG_CTRL_HEADER = 71,
        HWP_TAG_LIST_HEADER = 72,
        HWP_TAG_PAGE_DEF = 73,
        HWP_TAG_FOOTNOTE_SHAPE = 74,
        HWP_TAG_PAGE_BORDER_FILL = 75,
        HWP_TAG_SHAPE_COMPONENT = 76,
        HWP_TAG_TABLE = 77,
        HWP_TAG_SHAPE_COMPONENT_LINE = 78,
        HWP_TAG_SHAPE_COMPONENT_RECTANGLE = 79,
        HWP_TAG_SHAPE_COMPONENT_ELLIPSE = 80,
        HWP_TAG_SHAPE_COMPONENT_ARC = 81,
        HWP_TAG_SHAPE_COMPONENT_POLYGON = 82,
        HWP_TAG_SHAPE_COMPONENT_CURVE = 83,
        HWP_TAG_SHAPE_COMPONENT_OLE = 84,
        HWP_TAG_SHAPE_COMPONENT_PICTURE = 85,
        HWP_TAG_SHAPE_COMPONENT_CONTAINER = 86,
        HWP_TAG_CTRL_DATA = 87,
        HWP_TAG_EQEDIT = 88,
        HWP_TAG_RESERVED_89 = 89,
        HWP_TAG_SHAPE_COMPONENT_TEXTART = 90,
        HWP_TAG_FORM_OBJECT = 91,
        HWP_TAG_MEMO_SHAPE = 92,
        HWP_TAG_MEMO_LIST = 93,
        HWP_TAG_FORBIDDEN_CHAR = 94,
        HWP_TAG_CHART_DATA = 95,
        HWP_TAG_TRACK_CHANGE = 96,
        HWP_TAG_TRACK_CHANGE_AUTHOR = 97,

        HWP_TAG_SHAPE_COMPONENT_UNKNOWN = 115
    }
}
